version: '3.8'

services:
    pos:
        container_name: restaurant-pos2
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: 17.1-bullseye
                USERNAME: node
        environment:
            - PORT=3001
        stdin_open: true
