version: '3.8'

services:
  pos:
    container_name: restaurant-pos2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 17.1-bullseye
        USERNAME: node
    ports:
      - 3000:3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    stdin_open: true
