version: '3.8'

services:
    pos:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: 17.1-bullseye
                USERNAME: node
                USER_UID: 1000
        init: true
        environment:
          - PORT=3001
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        user: node
