version: '3.8'

services:
  pos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 17.1-bullseye
        USERNAME: node
        USER_UID: 1000
    init: true
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node
